# Generic template to build and test the application
# - Build
# - Test
# - Upload build artifacts

name: Build Website
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      build-folder:
        required: true
        type: string
      artifact-name:
        required: true
        type: string     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4            
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --no-watch --no-progress --browsers=ChromeHeadless
    # Upload build artifacts
    - uses: actions/upload-artifact@v4
      with:
       name: '${{ inputs.artifact-name }}'
       path: ${{ inputs.build-folder }}
  