# Deploys the application to the production
# - Build & Test
# - Upload Artifacts
# - Deploy artifacts to stage-slot 
# - Set traffic to 50/50
# - Swap slots
name: Build and deploy to staging/production

# Only trigger on pushes (merges) to main branch
on:
  push:
    branches: [ "main" ]

env:  
  AZURE_WEBAPP_PACKAGE_PATH: 'dist/todoapp/browser'  # build output folder
  WEBAPP_NAME: 'simple-todo' # name of the target app service in azure
  NODE_VERSION: '19.x'
  CI: true # According to https://github.com/orgs/community/discussions/25250, might be needed so npm test does not hang
  ARTEFACT_NAME: todo-app

jobs:
  # Ugly workaround because there is a bug that env.XY can not be used in reusable workflow parameters. see https://github.com/actions/runner/issues/2372#issuecomment-1591370444
  # Converts all env variables to output variables of this job which can then be used for reusable workflow parameters
  get-env-vars: 
    name: Get Environment vars
    runs-on: ubuntu-latest
    outputs:
      AZURE_WEBAPP_PACKAGE_PATH: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      WEBAPP_NAME: ${{ env.WEBAPP_NAME }}
      NODE_VERSION: ${{ env.NODE_VERSION }}
      ARTEFACT_NAME: ${{ env.ARTEFACT_NAME }}
    steps:
      - run: echo "null"

  # Call the build workflow
  build-app:
    needs: [get-env-vars]
    uses: ./.github/workflows/build.yml
    with:
      node-version: ${{ needs.get-env-vars.outputs.NODE_VERSION }}
      build-folder: ${{ needs.get-env-vars.outputs.AZURE_WEBAPP_PACKAGE_PATH }}
      artifact-name: ${{ needs.get-env-vars.outputs.ARTEFACT_NAME }}

  # Deploy to the stage slot of the production app service
  deploy-staging:
    uses: ./.github/workflows/deploy_azure.yml
    needs: [build-app,get-env-vars]    
    with:
      artifact-name: '${{ needs.get-env-vars.outputs.ARTEFACT_NAME }}'
      web-app-name: '${{ needs.get-env-vars.outputs.WEBAPP_NAME }}'
      slot-name: 'stage'
      environment-name: 'Staging'
    secrets: inherit

  # Set routing to 50/50
  set-routing:
    name: Set Routing for staging slot
    needs: deploy-staging
    runs-on: ubuntu-latest    
    steps:    
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set traffic for stage slot
      run: az webapp traffic-routing set --distribution stage=50 --name ${{ env.WEBAPP_NAME }} --resource-group ASE-2

  # Swap stage slot with production slot
  release-to-prod:
    name: Release to prod
    needs: set-routing
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: 'https://${{ env.WEBAPP_NAME }}.azurewebsites.net/'

    steps:    
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Swap slots
      run: az webapp deployment slot swap -s stage -n simple-todo -g ASE-2