# Builds the application and runs unit tests
name: Generic Build

# Trigger on each push to a feature-branch, and on every created pull request
on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "*" ]

env:  
  AZURE_WEBAPP_PACKAGE_PATH: 'dist/todoapp/browser' # build output folder
  NODE_VERSION: '19.x'   
  CI: true # According to https://github.com/orgs/community/discussions/25250, might be needed so npm test does not hang
  ARTEFACT_NAME: todo-app # name of the artifact which is uploaded to the pipeline

jobs:
  # Ugly workaround because there is a bug that env.XY can not be used in reusable workflow parameters. see https://github.com/actions/runner/issues/2372#issuecomment-1591370444
  # Converts all env variables to output variables of this job which can then be used for reusable workflow parameters
  get-env-vars: 
    name: Get Environment vars
    runs-on: ubuntu-latest
    outputs:
      AZURE_WEBAPP_PACKAGE_PATH: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      WEBAPP_NAME: ${{ env.WEBAPP_NAME }}
      NODE_VERSION: ${{ env.NODE_VERSION }}
      ARTEFACT_NAME: ${{ env.ARTEFACT_NAME }}
    steps:
      - run: echo "null"
  # Build application and run unit tests
  build-app:
    needs: [get-env-vars]
    uses: ./.github/workflows/build.yml
    with:      
      node-version: '${{ needs.get-env-vars.outputs.NODE_VERSION }}'
      build-folder: '${{ needs.get-env-vars.outputs.AZURE_WEBAPP_PACKAGE_PATH }}'
      artifact-name: '${{ needs.get-env-vars.outputs.ARTEFACT_NAME }}'
