
name: Build and deploy to development environment

on:
  push:
    branches: [ "development" ]

env:  
  AZURE_WEBAPP_PACKAGE_PATH: 'dist/todoapp/browser'      # Set this to the path to your web app project, defaults to the repository root
  WEBAPP_NAME: 'simple-todo-test'
  NODE_VERSION: '19.x'                # Set this to the node version to use
  CI: true # According to https://github.com/orgs/community/discussions/25250, might be needed so npm test does not hang
  ARTEFACT_NAME: todo-app

jobs:
  build-app:
    uses: ./.github/workflows/build.yml
    with:
      node-version: '19.x'
      build-folder: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
      artifact-name: '${{ env.ARTEFACT_NAME }}'
  deploy-develop:
    uses: ./.github/workflows/deploy_azure.yml
    needs: [build-app]    
    with:
      artifact-name: '${{ env.ARTEFACT_NAME }}'
      web-app-name: '${{ env.WEBAPP_NAME }}'
      environment-name: 'Development'
      slot-name: 'production'
    secrets: inherit