# Deploys the application to the test environment
# - Build & Test
# - Upload Artifacts
# - Deploy artifacts to development environment

name: Build and deploy to development environment

# only run on pushes (merges) to the development branch
on:
  push:
    branches: [ "development" ]

env:  
  AZURE_WEBAPP_PACKAGE_PATH: 'dist/todoapp/browser' # build output folder
  WEBAPP_NAME: 'simple-todo-test' # name of the target app service in azure
  NODE_VERSION: '19.x' 
  CI: true # According to https://github.com/orgs/community/discussions/25250, might be needed so npm test does not hang
  ARTEFACT_NAME: todo-app

jobs:
  # Ugly workaround because there is a bug that env.XY can not be used in reusable workflow parameters. see https://github.com/actions/runner/issues/2372#issuecomment-1591370444
  # Converts all env variables to output variables of this job which can then be used for reusable workflow parameters
  get-env-vars: 
    name: Get Environment vars
    runs-on: ubuntu-latest
    outputs:
      AZURE_WEBAPP_PACKAGE_PATH: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      WEBAPP_NAME: ${{ env.WEBAPP_NAME }}
      NODE_VERSION: ${{ env.NODE_VERSION }}
      ARTEFACT_NAME: ${{ env.ARTEFACT_NAME }}
    steps:
      - run: echo "null"
  
  # Call the build workflow
  build-app:
    needs: [get-env-vars]
    uses: ./.github/workflows/build.yml
    with:
      node-version: '${{ needs.get-env-vars.outputs.NODE_VERSION }}'
      build-folder: '${{ needs.get-env-vars.outputs.AZURE_WEBAPP_PACKAGE_PATH }}'
      artifact-name: '${{ needs.get-env-vars.outputs.ARTEFACT_NAME }}'
  
  # Deploy the build artifacts to azure app service
  deploy-develop:
    uses: ./.github/workflows/deploy_azure.yml
    needs: [build-app,get-env-vars]    
    with:
      artifact-name: '${{ needs.get-env-vars.outputs.ARTEFACT_NAME }}'
      web-app-name: '${{ needs.get-env-vars.outputs.WEBAPP_NAME }}'
      environment-name: 'Development'
      slot-name: 'production' # technically not needed here, as 'production' is default.
    secrets: inherit