# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:  
  AZURE_WEBAPP_PACKAGE_PATH: 'dist/todoapp/browser'      # Set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '19.x'                # Set this to the node version to use
  CI: true # According to https://github.com/orgs/community/discussions/25250, might be needed so npm test does not hang

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4            
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --no-watch --no-progress --browsers=ChromeHeadless
    - uses: actions/upload-artifact@v4
      with:
       name: 'app'
       path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  
  deploy-test:
    uses: ./.github/workflows/deploy_azure.yml
    needs: [build]    
    with:
      artifact-name: 'app'
      web-app-name: 'simple-todo-test'
      environment-name: 'Test'
      slot-name: 'production'
    secrets: inherit
  
  deploy-stage:
    uses: ./.github/workflows/deploy_azure.yml
    needs: [deploy-test]    
    with:
      artifact-name: 'app'
      web-app-name: 'simple-todo'
      slot-name: 'stage'
      environment-name: 'Staging'
    secrets: inherit

