# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: simple-todo-test   # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'dist/todoapp/browser'      # Set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '19.x'                # Set this to the node version to use
  CI: true # According to https://github.com/orgs/community/discussions/25250, might be needed so npm test does not hang

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4            
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --no-watch --no-progress --browsers=ChromeHeadless
    - uses: actions/upload-artifact@v4
      with:
       name: 'app'
       path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
     
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:        
        name: app    
        # Destination path. Supports basic tilde expansion.
        # Optional. Default is $GITHUB_WORKSPACE
        path: 'app'
    - uses: azure/login@v2
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy web app using Azure credentials
    - uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: app
    # Azure logout 
    - name: logout
      run: |
        az logout
